# filepath to file to submit
file: xceska06.tar.gz
# command for creating archive (leave blank if you dont want to create archive)
archive_command: tar -czf xceska06.tar.gz test1.txt text2.txt
# url of where to upload file
url: https://www.vut.cz/studis/student.phtml?sn=zadani_odevzdani&registrace_zadani_id=971964&apid=268279
#compares hasesh of uploaded and local file after upload
check: true
#where to download file after uploading for hash checking
#(folders will be created, files will be owerwritten!)
check_folder: test_folder
# for login with browser cookies fill in browser
browser:
# fill in path to yaml file with login information
login_file: /home/nod3zer0/login.yml
#broser_cokies/login_file/prompt
login_type: login_file
